language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir make
  - cd make
  - cmake .. && make tests
  - ./tests
addons:
  apt:
    packages:
      - libunittest++-dev
before_install:
  - brew install cmake
  - brew install unittest-cpp
matrix:
  include:
    - os: osx
    - os: linux