language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir make
  - cd make
  - cmake .. && make tests
  - ./tests
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libunittest++-dev libcurl4-openssl-dev; else brew install unittest-cpp; fi
matrix:
  include:
    - os: osx
    - os: linux