language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir make
  - cd make
  - if [ $TRAVIS_OS_NAME = linux ]; then cmake -DUTPP_INCLUDE_DIRS=/usr/include ..; else cmake ..; fi
  - make tests
  - ./tests
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libunittest++-dev libcurl4-openssl-dev; else brew install unittest-cpp; fi
matrix:
  include:
    - os: osx
    - os: linux