language: cpp
compiler:
  - clang
  - gcc
script:
  - mkdir make
  - cd make
  - cmake .. && make tests
  - ./tests
matrix:
  include:
    - os: osx
      env:
        - MATRIX_EVAL="brew install cmake && brew install unittest-cpp"
    - os: linux
      addons:
        apt:
          packages:
            - libunittest++-dev