language: cpp
sudo: required
services:
  - docker
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo docker pull centos:centos${OS_VERSION}; fi
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo docker run --mount type=bind,source="${TRAVIS_BUILD_DIR}",target="/home/build" -it centos:centos${OS_VERSION} /bin/bash -c "yum -y install epel-release && yum -y install gcc-c++ make cmake3 libcurl-devel unittest-cpp-devel && cd /home/build && mkdir make && cd make && cmake3 -DCMAKE_CXX_COMPILER=/usr/bin/c++ .. && make tests"; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install unittest-cpp && cd "${TRAVIS_BUILD_DIR}" && mkdir make && cd make && cmake .. && make tests; fi
script:
  - cd "${TRAVIS_BUILD_DIR}" && cd make && ./tests
matrix:
  include:
    - os: osx
    - os: linux